run:
  # Timeout for analysis, e.g. 30s, 5m
  timeout: 5m

linters:
  disable:
    - unused       # 禁用未使用代码检查
    - gocyclo      # 禁用圈复杂度检查
    - gocritic     # 禁用代码风格检查

linters-settings:
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - hugeParam
      - rangeValCopy

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: server/base\.go
      text: "exported method (\\w+\\.)(\\w+) should have comment or be unexported"
      linters:
        - golint
    - path: transport/
      text: "exported method (\\w+\\.)(\\w+) should have comment or be unexported"
      linters:
        - golint
    # 排除已废弃但保留的向后兼容函数
    - path: transport/http\.go
      text: "func .* is unused"
      linters:
        - unused
    - path: transport/websocket\.go
      text: "func .* is unused"
      linters:
        - unused
    - path: transport/websocket\.go
      text: "field .* is unused"
      linters:
        - unused
    # 排除命名返回值问题
    - text: "unnamedResult"
      linters:
        - gocritic
    # 排除参数类型组合问题
    - text: "paramTypeCombine"
      linters:
        - gocritic
    # 排除字符串比较问题
    - text: "stringXbytes"
      linters:
        - gocritic
    # 排除 else if 格式问题
    - text: "elseif"
      linters:
        - gocritic
    # 排除 http.NoBody 建议
    - text: "httpNoBody"
      linters:
        - gocritic

  # Maximum issues count per one linter. Set to 0 to disable.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable.
  max-same-issues: 0 