package response

import (
	"errors"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/virgoC0der/go-mcp/internal/types"
)

func TestHandleJSONRPCError(t *testing.T) {
	id := "err-req-1"

	// Test with types.Error
	mcpErr := &types.Error{
		Code:    "not_found",
		Message: "Resource X not found",
	}
	respMCP := HandleJSONRPCError(id, mcpErr)
	assert.Equal(t, id, respMCP.ID)
	assert.NotNil(t, respMCP.Error)
	assert.Equal(t, MapMCPErrorToJSONRPCCode(mcpErr.Code), respMCP.Error.Code)
	assert.Equal(t, mcpErr.Message, respMCP.Error.Message)
	assert.Equal(t, mcpErr, respMCP.Error.Data) // Should include original MCP error as data
	assert.Nil(t, respMCP.Result)

	// Test with generic error
	genericErr := errors.New("a generic error occurred")
	respGeneric := HandleJSONRPCError(id, genericErr)
	assert.Equal(t, id, respGeneric.ID)
	assert.NotNil(t, respGeneric.Error)
	assert.Equal(t, -32603, respGeneric.Error.Code) // Default internal error code
	assert.Equal(t, genericErr.Error(), respGeneric.Error.Message)
	assert.Nil(t, respGeneric.Error.Data) // No data for generic errors
	assert.Nil(t, respGeneric.Result)
}

func TestMarshalResponse(t *testing.T) {
	tests := []struct {
		name        string
		response    JSONRPCResponse
		expectJSON  string
		expectError bool
	}{
		{
			name: "successful response",
			response: JSONRPCResponse{
				JSONRPC: "2.0",
				ID:      1,
				Result:  map[string]string{"status": "ok"},
			},
			expectJSON:  `{"jsonrpc":"2.0","id":1,"result":{"status":"ok"}}`,
			expectError: false,
		},
		{
			name: "error response",
			response: JSONRPCResponse{
				JSONRPC: "2.0",
				ID:      "req-err",
				Error:   &JSONRPCError{Code: -32000, Message: "Failed"},
			},
			expectJSON:  `{"jsonrpc":"2.0","id":"req-err","error":{"code":-32000,"message":"Failed"}}`,
			expectError: false,
		},
		{
			name: "unmarshalable result",
			response: JSONRPCResponse{
				JSONRPC: "2.0",
				ID:      2,
				Result:  make(chan int), // Cannot be marshaled
			},
			// Expect a simplified error response generated by MarshalResponse itself
			expectJSON:  `{"jsonrpc":"2.0","id":2,"error":{"code":-32603,"message":"Failed to marshal response: json: unsupported type: chan int"}}`,
			expectError: false, // MarshalResponse handles the error internally
		},
		{
			name: "unmarshalable error data",
			response: JSONRPCResponse{
				JSONRPC: "2.0",
				ID:      3,
				Error:   &JSONRPCError{Code: -32001, Message: "Data error", Data: make(chan bool)},
			},
			// Expect a simplified error response
			expectJSON:  `{"jsonrpc":"2.0","id":3,"error":{"code":-32603,"message":"Failed to marshal response: json: unsupported type: chan bool"}}`,
			expectError: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			data, err := MarshalResponse(tt.response)

			if tt.expectError {
				assert.Error(t, err)
				assert.Nil(t, data)
			} else {
				assert.NoError(t, err)
				assert.JSONEq(t, tt.expectJSON, string(data))
			}
		})
	}
}
